# 默认配置
server:
  port: 9380
  servlet:
    context-path: /distributedid
spring:
  application:
    name: distributedid-service
  # 多数据源
  datasource:
    dynamic:
      datasource:
        master_1:
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:33061/id_config?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_2:
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:33062/id_config?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus
mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-underline: true
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.leeyom.distributedid.domain.entity

# 监控
javamelody:
  enabled: true
  init-parameters:
    log: true